# Generated by Django 5.1.1 on 2024-09-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_alter_donor_address_alter_donor_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
    ]
